### PR TITLE
Use quotes to escape the Solr special characters

### LINKED ISSUE #4: Konosuba does not gets scrobled
On S01E01, you get "TypeError: failed to fetch":

image

On S01E02, you get "Could not find matching episode on Trakt"

image

I feel that is related to the matching of Crunchyroll Names with Trakt Show Names, because the name on Crunchyroll is:

```
KONOSUBA -God's blessing on this wonderful world!
```

And on Trakt is:
```
KonoSuba: God's Blessing on This Wonderful World!
```

### PR DESCRIPTION
**Pull request by justalemon**
Fixes #4 

Here is a test when watching S01E09:

image

Here is what Trakt sees when I'm watching S01E01:

image

### CODE REVIEW

**Comment by sttz** [comment]
Thanks! What's the reason for escaping the quotation marks?

I fixed this in c727b44 and also added escaping of quotation marks inside the title, which could lead to issues.

**Comment by justalemon** [comment]
Well, is not really escaping the quotation marks. It literally places the title between two quotation marks, as you mentioned in trakt/api-help#76. This is the cleanest and safest way, because it tells Trakt/Solr to search for the string as-is.

**Comment by sttz** [comment]
Yeah, that was clear. I was just unsure why you added backslashes to the " marks inside a string using ` marks, where they are not required.

I thought the backslashes would be included in the string, but it seems they get stripped, i.e.

    `"hello"`.length; // equals 7
    `\"hello\"`.length; // also equals 7
    `"hello"` === `\"hello\"`; // is true

**Comment by justalemon** [comment]
Sorry, I didn't knew about that. I barely know the basics of Javascript/Typescript.

**Comment by justalemon** [comment]
Still, it would be better to send the title as-is (by using double quotes) instead of messing with it. You said:

> I would prefer not to mess with the title being looked up

And I agree, because most of the time the titles will match against the database when sent.

**Comment by sttz** [comment]
That's what I'm doing. But you can't just put the title in quotes, because if the title itself includes quotes, they would undo the outer quoting.

i.e. (**bold** = quoted literal string)
> "**KONOSUBA -God's blessing on this wonderful world!**"

works fine but

> "**Made Up Title** "With an -Inner Quote" **and Some More**"

Would be interpreted as two quoted strings, with a search query in-between. And `-Inner` would be taken as an exclusion, just like `-God's` was.

**Pull request closed without merging**
